version: '3.8'

services:
  postgres:
    container_name: charity_postgres
    image: postgres:14-alpine
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
